### PR TITLE
Fix the documentation according to the new dashboard

### PR DESCRIPTION
**Pull request by DanielGherasim**
And other cosmetic improvements

Redirects required so we have no broken links:

- total/migration-from-obsolete-aspose-storage-cloud-to-micro-service-based-cloud-storage/+ => total/aspose-storage-cloud/

- total/aspose-cloud-ui-help-topics/+ => total/getting-started/dashboard/
- total/creating-and-managing-account/+ => total/getting-started/dashboard/creating-and-managing-account/
- total/create-new-app-and-get-app-key-and-sid/+ => total/getting-started/dashboard/creating-and-managing-application/
- total/how-to-configure-3rd-party-cloud-storages/+ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/
- total/configure-amazon-s3-storage/+ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/configure-amazon-s3-storage/
- total/configure-azure-storage/+ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/configure-azure-storage/
- total/configure-dropbox-storage/+ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/configure-dropbox-storage/
- total/configure-ftp-storage/+ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/configure-ftp-storage/
- total/configure-google-drive-storage/ => total/getting-started/dashboard/how-to-configure-3rd-party-cloud-storages/configure-google-drive-storage/

- total/overview-of-aspose-cloud-rest-api/+ => total/getting-started/rest-api-overview/
- total/authenticating-api-requests/+ => total/getting-started/rest-api-overview/authenticating-api-requests/
- total/json-web-token-authentication/+ => total/getting-started/rest-api-overview/authenticating-api-requests/
- storage/json-web-token-authentication/+ => total/getting-started/rest-api-overview/authenticating-api-requests/
- total/request-format/+ => total/getting-started/rest-api-overview/request-format/
- total/response-format/+ => total/getting-started/rest-api-overview/response-format/
- total/how-to-work-with-files-and-storage/+ => /total/getting-started/dashboard/how-to-work-with-files-and-storage/
- total/how-to-work-with-api-usage-logs/+ => /total/getting-started/dashboard/how-to-work-with-api-usage-logs/
- https://docs.aspose.cloud/display/taskscloud/Working+with+Files+and+Storage+using+Aspose.Tasks+Cloud => tasks/working-with-files-and-storage/
- https://docs.aspose.cloud/display/storagecloud/JSON+Web+Token+Authentication => total/getting-started/rest-api-overview/authenticating-api-requests/
- https://docs.aspose.cloud/display/totalcloud/Aspose+Cloud+UI+Help+Topics => total/getting-started/dashboard/

### CODE REVIEW

**Comment by victorkrivolapaspose** [comment]
@DanielGherasim,

In the redirection list, I can't understand the following lines:

total/request-format/+ =>
total/response-format/+ =>

There is no information where listed URLs must be redirected to. Please explain. Also, what does "+" mean? Thanks.

**Comment by DanielGherasim** [comment]
@victorkrivolapaspose ,

> @DanielGherasim,
> 
> In the redirection list, I can't understand the following lines:
> 
> total/request-format/+ =>
> total/response-format/+ =>
> 

I have Edited my comment and completed the redirect URIs for the specified current URLs.

>
> There is no information where listed URLs must be redirected to. Please explain. Also, what does "+" mean? Thanks.
>
The "+" sign means with or without the trailing slash '/'

**Comment by muhammad-ijaz** [comment]
@DanielGherasim 

Can you please explain this redirect (total/migration-from-obsolete-aspose-storage-cloud-to-micro-service-based-cloud-storage/+ => total/aspose-storage-cloud/) as well? We are going to discontinue Aspose.Storage Cloud and everything related to Aspose.Storage Cloud will be removed after 31st December (when the official notice period ends). total/migration-from-obsolete-aspose-storage-cloud-to-micro-service-based-cloud-storage/ was added to tell the users about this change.

**Comment by DanielGherasim** [comment]
> @DanielGherasim
> 
> Can you please explain this redirect (total/migration-from-obsolete-aspose-storage-cloud-to-micro-service-based-cloud-storage/+ => total/aspose-storage-cloud/) as well? We are going to discontinue Aspose.Storage Cloud and everything related to Aspose.Storage Cloud will be removed after 31st December (when the official notice period ends). total/migration-from-obsolete-aspose-storage-cloud-to-micro-service-based-cloud-storage/ was added to tell the users about this change.

@muhammad-ijaz,

I have moved everything about noticing the customers about retiring and migrating from Aspose.Storage Cloud to 'Storage in Products' on that page (/total/aspose-storage-cloud). The menu looks better and also I think it's clearer and easier to found about how to use storage in the new way.

**Comment by muhammad-ijaz** [comment]
@victorkrivolapaspose 

The changes made by @DanielGherasim look good to me. Please merge the pull request or let me know once the redirects are added.

**Comment by DanielGherasim** [comment]
@victorkrivolapaspose, @muhammad-ijaz,

https://docs.aspose.cloud

I do not have access to edit the main page so I'm asking here what change is required also there:

* Please remove Aspose.Storage Cloud from https://docs.aspose.cloud

**Comment by muhammad-ijaz** [comment]
@DanielGherasim 

>Please remove Aspose.Storage Cloud from https://docs.aspose.cloud

It has been removed from the main page.

**Comment by victorkrivolapaspose** [comment]
> 
> 
> @victorkrivolapaspose
> 
> The changes made by @DanielGherasim look good to me. Please merge the pull request or let me know once the redirects are added.

@muhammad-ijaz, I have added the redirects.

**Pull request merged**
